### ISSUE TITLE
Console logs of update values are undefined

### ISSUE THREAD

**Issue by millisande** [botmasterai/botmaster-watson-conversation-ware#1]
[Watson_Example_Bug.zip](https://github.com/botmasterai/botmaster-watson-conversation-ware/files/907628/Watson_Example_Bug.zip)

`botmaster.use({
  type: 'incoming',
  name: 'my-awesome-middleware',
  controller: (bot, update) => {
    console.log(update.watsonUpdate);
    console.log(update.session.watsonContext);
    console.log(update.watson);
    // watsonUpdate.output.text is an array as watson can reply with a few
   // messages one after another
   return bot.sendTextCascadeTo(update.watsonUpdate.output.text, update.sender.id);
 }
})`

When this section of the code is run on a simple socket.io project running locally all of the printed values are undefined and the sendTextCascadeTo function fails and causes an error because update.watsonUpdate is undefined. 

If you can explain why my example code does not work that would be great, thanks.

**Comment by jwickens** [comment]
Can you enable debug with `export DEBUG=botmaster:*` and tell me what the output is when running the code? Also can you verify if the update has `update.message.text` defined.

**Comment by millisande** [comment]
the update.message.text is also undefined. Do you have an example about how to use export DEBUG = botmaster: * do I put that in the console or do I have to import the debug library and then put it in my code?

**Comment by jdwuarin** [comment]
This issue is almost certainly caused by a breaking change I made in botmaster-socket.io for botmaster 3. The object sent to the server from the client should now have the same structure as the one you would have in the backend. So if sending text, the text should be at yourObjectYourSending.message.text. Whereas it used to be at yourObjectYourSending.text prior to that change. Hope that makes sense. @jwickens, would be great if you could update the botmaster-socket.io Readme to reflect that as I can't do that in any easy way from my phone.

**Comment by jwickens** [comment]
@millisande can you confirm if adjusting the structure of the message sent by the socket.io client has helped? I've updated the readme here https://github.com/botmasterai/botmaster-socket.io to have the correct payload with the v3 changes

**Comment by jdwuarin** [comment]
Thanks for that @jwickens. Could you also update  the client side code at the top of the Readme? In the Code section.

**Comment by jwickens** [comment]
Oops missed that one @jdwuarin - fixed now

**Comment by millisande** [comment]
Brilliant thank you! (✿◠‿◠) it's working now
